import "./globals.scss";
import { Inter } from "next/font/google";

import UserBage from "@/components/Layout/UserBage/UserBage";
import Navigation from "@/components/Layout/Navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='layout container'>
        <UserBage/>
        <Navigation/>
        <div className='main'>
          {children}
        </div>
      </body>
    </html>
  );
}
