"use client";

import "./globals.scss";

import { usePathname } from "next/navigation";

import { Provider } from "react-redux";

import UserInfo from "@/components/Layout/UserInfo/UserInfo";
import Navigation from "@/components/Layout/Navigation/Navigation";
import Auth from "@/components/Auth/Auth";

import { store } from "@/redux/store";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname();

  return (
    <html lang="en">
      <Provider store={store}>
        <body className={pathname === "/auth" || '/auth/genres' ? "flex items-center justify-center h-screen" : ""}>
          {pathname === "/auth" || '/auth/genres' ? children :
            <div className='layout container relative'>
              <div className="aside fixed top-6 ">
                <UserInfo />
                <Navigation />
              </div>
              <div className='main'>
                {children}
              </div>
            </div>
          }
        </body>
      </Provider>
    </html>
  );
}
